# MySQL
mysql:
  user: mysqluser
  pass: mysqlpass
  host: localhost
  port: 3306
  db: mysqldb

# Reddit
reddit:
  user: mybotuser
  pass: mybotpass
  batch-limit: 1000
  useragent: /u/mybotuser
  help-url: http://www.reddit.com/r/mybotuser/wiki/index
  comments:
    verify: true
    pending: false
    expired: false

# Other
misc:
  qr-service-url: 'https://chart.googleapis.com/chart?cht=qr&choe=UTF-8&chs=300x300&chl='
  sleep-time: 30
  expire-pending-hours: 48

# Regex
regex:
  amount: '([0-9]{1,6}(?:\.[0-9]{0,6})?)'
  keywords:
    tip: '(givetip|altcointip|alttip|alt)'
    info: '(info)'
    register: '(register)'
    accept: '(accept)'
    decline: '(decline)'
    withdraw: '(withdraw)'
    history: '(history)'

# Logging
logging:
  info-log-filename: ctb-info.log
  debug-log-filename: ctb-debug.log

# Cryptocoins
cc:
  # Bitcoin
  btc:
    enabled: false
    unit: btc
    name: Bitcoin
    confile: '~/.bitcoin/bitcoin.conf'
    minconf:
      tip: 1
      withdraw: 10
    txmin: 0.05
    txfee: 0.0005
    walletpassphrase: mypass1
    explorer:
      address: 'http://blockchain.info/address/'
      transaction: 'http://blockchain.info/tx/'
    regex:
      address: '([1|3][1-9a-z]{20,40})'
      units: '(btc|bitcoin|bitcoins)'
  # Litecoin
  ltc:
    enabled: false
    unit: ltc
    name: Litecoin
    conf-file: '~/.litecoin/litecoin.conf'
    minconf:
      tip: 1
      withdraw: 10
    txmin: 0.25
    txfee: 0.01
    walletpassphrase: mypass1
    explorer:
      address: 'http://explorer.litecoin.net/address/'
      transaction: 'http://explorer.litecoin.net/tx/'
    regex:
      address: '(L[1-9a-z]{20,40})'
      units: '(ltc|litecoin|litecoins)'
  # PPCoin
  ppc:
    enabled: false
    unit: ppc
    name: PPCoin
    conf-file: '~/.ppcoin/ppcoin.conf'
    minconf:
      tip: 1
      withdraw: 10
    txmin: 0.5
    txfee: 0.01
    walletpassphrase: mypass1
    explorer:
      address: 'http://www.cryptocoinexplorer.com:2750/address/'
      transaction: 'http://www.cryptocoinexplorer.com:2750/tx/'
    regex:
      address: '(P[1-9a-z]{20,40})'
      units: '(ppc|ppcoin|ppcoins)'
  # Namecoin
  nmc:
    enabled: false
    unit: nmc
    name: Namecoin
    conf-file: '~/.namecoin/bitcoin.conf'
    minconf:
      tip: 1
      withdraw: 10
    txmin: 0.5
    txfee: 0.01
    explorer:
      address: 'http://explorer.dot-bit.org/a/'
      transaction: 'http://explorer.dot-bit.org/tx/'
    regex:
      address: '([N|M][1-9a-z]{20,40})'
      units: '(nmc|namecoin|namecoins)'
  # Novacoin
  nvc:
    enabled: false
    unit: nvc
    name: Novacoin
    conf-file: '~/.novacoin/novacoin.conf'
    minconf:
      tip: 1
      withdraw: 10
    txmin: 0.5
    txfee: 0.01
    explorer:
      address: 'http://www.cryptocoinexplorer.com:6750/address/'
      transaction: 'http://www.cryptocoinexplorer.com:6750/tx/'
    regex:
      address: '(4[1-9a-z]{20,40})'
      units: '(nvc|novacoin|novacoins)'
