mysql-user : cointipbot
mysql-pass : randompass1234
mysql-host : localhost
mysql-port : 3306
mysql-db: cointipbot

bitcoind-enabled : true
litecoind-enabled : true
ppcoind-enabled : true

reddit-username : mycointipbotuser
reddit-pass : randompass1234
reddit-useragent : /u/mycointipbotuser
reddit-botsubreddit : mycointipbotsubreddit

admin-email : admin@example.com
